apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database
  labels:
    app: mysql-database
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql-database

  template:
    metadata:
      labels:
        app: mysql-database
    spec:
      containers:
        - image: mysql:8
          name: mysql-database
          args:
            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-persistent-claim
