apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: default
data:
  DB_URL: jdbc:mysql://mysql-service:3306/users
  ORDER_URL: http://order-service
  USER_URL: http://user-service
  JAGER_HOST_URL: jaeger-agent